var COMPILED=!0,goog=goog||{};goog.global=this;goog.isDef=function(a){return void 0!==a};goog.exportPath_=function(a,b,c){a=a.split(".");c=c||goog.global;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&goog.isDef(b)?c[d]=b:c=c[d]?c[d]:c[d]={}};
goog.define=function(a,b){var c=b;COMPILED||(goog.global.CLOSURE_UNCOMPILED_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_UNCOMPILED_DEFINES,a)?c=goog.global.CLOSURE_UNCOMPILED_DEFINES[a]:goog.global.CLOSURE_DEFINES&&Object.prototype.hasOwnProperty.call(goog.global.CLOSURE_DEFINES,a)&&(c=goog.global.CLOSURE_DEFINES[a]));goog.exportPath_(a,c)};goog.DEBUG=!0;goog.LOCALE="en";goog.TRUSTED_SITE=!0;goog.STRICT_MODE_COMPATIBLE=!1;goog.DISALLOW_TEST_ONLY_CODE=COMPILED&&!goog.DEBUG;
goog.provide=function(a){if(!COMPILED&&goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');goog.constructNamespace_(a)};goog.constructNamespace_=function(a,b){if(!COMPILED){delete goog.implicitNamespaces_[a];for(var c=a;(c=c.substring(0,c.lastIndexOf(".")))&&!goog.getObjectByName(c);)goog.implicitNamespaces_[c]=!0}goog.exportPath_(a,b)};goog.VALID_MODULE_RE_=/^[a-zA-Z_$][a-zA-Z0-9._$]*$/;
goog.module=function(a){if(!goog.isString(a)||!a||-1==a.search(goog.VALID_MODULE_RE_))throw Error("Invalid module identifier");if(!goog.isInModuleLoader_())throw Error("Module "+a+" has been loaded incorrectly.");if(goog.moduleLoaderState_.moduleName)throw Error("goog.module may only be called once per module.");goog.moduleLoaderState_.moduleName=a;if(!COMPILED){if(goog.isProvided_(a))throw Error('Namespace "'+a+'" already declared.');delete goog.implicitNamespaces_[a]}};goog.module.get=function(a){return goog.module.getInternal_(a)};
goog.module.getInternal_=function(a){if(!COMPILED)return goog.isProvided_(a)?a in goog.loadedModules_?goog.loadedModules_[a]:goog.getObjectByName(a):null};goog.moduleLoaderState_=null;goog.isInModuleLoader_=function(){return null!=goog.moduleLoaderState_};goog.module.declareTestMethods=function(){if(!goog.isInModuleLoader_())throw Error("goog.module.declareTestMethods must be called from within a goog.module");goog.moduleLoaderState_.declareTestMethods=!0};
goog.module.declareLegacyNamespace=function(){if(!COMPILED&&!goog.isInModuleLoader_())throw Error("goog.module.declareLegacyNamespace must be called from within a goog.module");if(!COMPILED&&!goog.moduleLoaderState_.moduleName)throw Error("goog.module must be called prior to goog.module.declareLegacyNamespace.");goog.moduleLoaderState_.declareLegacyNamespace=!0};
goog.setTestOnly=function(a){if(goog.DISALLOW_TEST_ONLY_CODE)throw a=a||"",Error("Importing test-only code into non-debug environment"+(a?": "+a:"."));};goog.forwardDeclare=function(a){};COMPILED||(goog.isProvided_=function(a){return a in goog.loadedModules_||!goog.implicitNamespaces_[a]&&goog.isDefAndNotNull(goog.getObjectByName(a))},goog.implicitNamespaces_={"goog.module":!0});
goog.getObjectByName=function(a,b){for(var c=a.split("."),d=b||goog.global,e;e=c.shift();)if(goog.isDefAndNotNull(d[e]))d=d[e];else return null;return d};goog.globalize=function(a,b){var c=b||goog.global,d;for(d in a)c[d]=a[d]};goog.addDependency=function(a,b,c,d){if(goog.DEPENDENCIES_ENABLED){var e;a=a.replace(/\\/g,"/");for(var f=goog.dependencies_,g=0;e=b[g];g++)f.nameToPath[e]=a,f.pathIsModule[a]=!!d;for(d=0;b=c[d];d++)a in f.requires||(f.requires[a]={}),f.requires[a][b]=!0}};
goog.ENABLE_DEBUG_LOADER=!0;goog.logToConsole_=function(a){goog.global.console&&goog.global.console.error(a)};
goog.require=function(a){if(!COMPILED){goog.ENABLE_DEBUG_LOADER&&goog.IS_OLD_IE_&&goog.maybeProcessDeferredDep_(a);if(goog.isProvided_(a))return goog.isInModuleLoader_()?goog.module.getInternal_(a):null;if(goog.ENABLE_DEBUG_LOADER){var b=goog.getPathFromDeps_(a);if(b)return goog.included_[b]=!0,goog.writeScripts_(),null}a="goog.require could not find: "+a;goog.logToConsole_(a);throw Error(a);}};goog.basePath="";goog.nullFunction=function(){};goog.identityFunction=function(a,b){return a};
goog.abstractMethod=function(){throw Error("unimplemented abstract method");};goog.addSingletonGetter=function(a){a.getInstance=function(){if(a.instance_)return a.instance_;goog.DEBUG&&(goog.instantiatedSingletons_[goog.instantiatedSingletons_.length]=a);return a.instance_=new a}};goog.instantiatedSingletons_=[];goog.LOAD_MODULE_USING_EVAL=!0;goog.SEAL_MODULE_EXPORTS=goog.DEBUG;goog.loadedModules_={};goog.DEPENDENCIES_ENABLED=!COMPILED&&goog.ENABLE_DEBUG_LOADER;
goog.DEPENDENCIES_ENABLED&&(goog.included_={},goog.dependencies_={pathIsModule:{},nameToPath:{},requires:{},visited:{},written:{},deferred:{}},goog.inHtmlDocument_=function(){var a=goog.global.document;return"undefined"!=typeof a&&"write"in a},goog.findBasePath_=function(){if(goog.global.CLOSURE_BASE_PATH)goog.basePath=goog.global.CLOSURE_BASE_PATH;else if(goog.inHtmlDocument_())for(var a=goog.global.document.getElementsByTagName("script"),b=a.length-1;0<=b;--b){var c=a[b].src,d=c.lastIndexOf("?"),
d=-1==d?c.length:d;if("base.js"==c.substr(d-7,7)){goog.basePath=c.substr(0,d-7);break}}},goog.importScript_=function(a,b){(goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_)(a,b)&&(goog.dependencies_.written[a]=!0)},goog.IS_OLD_IE_=goog.global.document&&goog.global.document.all&&!goog.global.atob,goog.importModule_=function(a){goog.importScript_("",'goog.retrieveAndExecModule_("'+a+'");')&&(goog.dependencies_.written[a]=!0)},goog.queuedModules_=[],goog.wrapModule_=function(a,b){return goog.LOAD_MODULE_USING_EVAL&&
goog.isDef(goog.global.JSON)?"goog.loadModule("+goog.global.JSON.stringify(b+"\n//# sourceURL="+a+"\n")+");":'goog.loadModule(function(exports) {"use strict";'+b+"\n;return exports});\n//# sourceURL="+a+"\n"},goog.loadQueuedModules_=function(){var a=goog.queuedModules_.length;if(0<a){var b=goog.queuedModules_;goog.queuedModules_=[];for(var c=0;c<a;c++)goog.maybeProcessDeferredPath_(b[c])}},goog.maybeProcessDeferredDep_=function(a){goog.isDeferredModule_(a)&&goog.allDepsAreAvailable_(a)&&(a=goog.getPathFromDeps_(a),
goog.maybeProcessDeferredPath_(goog.basePath+a))},goog.isDeferredModule_=function(a){return(a=goog.getPathFromDeps_(a))&&goog.dependencies_.pathIsModule[a]?goog.basePath+a in goog.dependencies_.deferred:!1},goog.allDepsAreAvailable_=function(a){if((a=goog.getPathFromDeps_(a))&&a in goog.dependencies_.requires)for(var b in goog.dependencies_.requires[a])if(!goog.isProvided_(b)&&!goog.isDeferredModule_(b))return!1;return!0},goog.maybeProcessDeferredPath_=function(a){if(a in goog.dependencies_.deferred){var b=
goog.dependencies_.deferred[a];delete goog.dependencies_.deferred[a];goog.globalEval(b)}},goog.loadModule=function(a){var b=goog.moduleLoaderState_;try{goog.moduleLoaderState_={moduleName:void 0,declareTestMethods:!1};var c;if(goog.isFunction(a))c=a.call(goog.global,{});else if(goog.isString(a))c=goog.loadModuleFromSource_.call(goog.global,a);else throw Error("Invalid module definition");var d=goog.moduleLoaderState_.moduleName;if(!goog.isString(d)||!d)throw Error('Invalid module name "'+d+'"');goog.moduleLoaderState_.declareLegacyNamespace?
goog.constructNamespace_(d,c):goog.SEAL_MODULE_EXPORTS&&Object.seal&&Object.seal(c);goog.loadedModules_[d]=c;if(goog.moduleLoaderState_.declareTestMethods)for(var e in c)if(0===e.indexOf("test",0)||"tearDown"==e||"setUp"==e||"setUpPage"==e||"tearDownPage"==e)goog.global[e]=c[e]}finally{goog.moduleLoaderState_=b}},goog.loadModuleFromSource_=function(a){eval(a);return{}},goog.writeScriptTag_=function(a,b){if(goog.inHtmlDocument_()){var c=goog.global.document;if("complete"==c.readyState){if(/\bdeps.js$/.test(a))return!1;
throw Error('Cannot write "'+a+'" after document load');}var d=goog.IS_OLD_IE_;void 0===b?d?(d=" onreadystatechange='goog.onScriptLoad_(this, "+ ++goog.lastNonModuleScriptIndex_+")' ",c.write('<script type="text/javascript" src="'+a+'"'+d+">\x3c/script>")):c.write('<script type="text/javascript" src="'+a+'">\x3c/script>'):c.write('<script type="text/javascript">'+b+"\x3c/script>");return!0}return!1},goog.lastNonModuleScriptIndex_=0,goog.onScriptLoad_=function(a,b){"complete"==a.readyState&&goog.lastNonModuleScriptIndex_==
b&&goog.loadQueuedModules_();return!0},goog.writeScripts_=function(){function a(e){if(!(e in d.written)){if(!(e in d.visited)&&(d.visited[e]=!0,e in d.requires))for(var f in d.requires[e])if(!goog.isProvided_(f))if(f in d.nameToPath)a(d.nameToPath[f]);else throw Error("Undefined nameToPath for "+f);e in c||(c[e]=!0,b.push(e))}}var b=[],c={},d=goog.dependencies_,e;for(e in goog.included_)d.written[e]||a(e);for(var f=0;f<b.length;f++)e=b[f],goog.dependencies_.written[e]=!0;var g=goog.moduleLoaderState_;
goog.moduleLoaderState_=null;for(f=0;f<b.length;f++)if(e=b[f])d.pathIsModule[e]?goog.importModule_(goog.basePath+e):goog.importScript_(goog.basePath+e);else throw goog.moduleLoaderState_=g,Error("Undefined script input");goog.moduleLoaderState_=g},goog.getPathFromDeps_=function(a){return a in goog.dependencies_.nameToPath?goog.dependencies_.nameToPath[a]:null},goog.findBasePath_(),goog.global.CLOSURE_NO_DEPS||goog.importScript_(goog.basePath+"deps.js"));
goog.normalizePath_=function(a){a=a.split("/");for(var b=0;b<a.length;)"."==a[b]?a.splice(b,1):b&&".."==a[b]&&a[b-1]&&".."!=a[b-1]?a.splice(--b,2):b++;return a.join("/")};
goog.retrieveAndExecModule_=function(a){if(!COMPILED){var b=a;a=goog.normalizePath_(a);var c=goog.global.CLOSURE_IMPORT_SCRIPT||goog.writeScriptTag_,d=null,e=new goog.global.XMLHttpRequest;e.onload=function(){d=this.responseText};e.open("get",a,!1);e.send();d=e.responseText;if(null!=d)e=goog.wrapModule_(a,d),goog.IS_OLD_IE_?(goog.dependencies_.deferred[b]=e,goog.queuedModules_.push(b)):c(a,e);else throw Error("load of "+a+"failed");}};
goog.typeOf=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if("function"==b&&"undefined"==typeof a.call)return"object";return b};goog.isNull=function(a){return null===a};goog.isDefAndNotNull=function(a){return null!=a};goog.isArray=function(a){return"array"==goog.typeOf(a)};goog.isArrayLike=function(a){var b=goog.typeOf(a);return"array"==b||"object"==b&&"number"==typeof a.length};goog.isDateLike=function(a){return goog.isObject(a)&&"function"==typeof a.getFullYear};goog.isString=function(a){return"string"==typeof a};
goog.isBoolean=function(a){return"boolean"==typeof a};goog.isNumber=function(a){return"number"==typeof a};goog.isFunction=function(a){return"function"==goog.typeOf(a)};goog.isObject=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b};goog.getUid=function(a){return a[goog.UID_PROPERTY_]||(a[goog.UID_PROPERTY_]=++goog.uidCounter_)};goog.hasUid=function(a){return!!a[goog.UID_PROPERTY_]};goog.removeUid=function(a){"removeAttribute"in a&&a.removeAttribute(goog.UID_PROPERTY_);try{delete a[goog.UID_PROPERTY_]}catch(b){}};
goog.UID_PROPERTY_="closure_uid_"+(1E9*Math.random()>>>0);goog.uidCounter_=0;goog.getHashCode=goog.getUid;goog.removeHashCode=goog.removeUid;goog.cloneObject=function(a){var b=goog.typeOf(a);if("object"==b||"array"==b){if(a.clone)return a.clone();var b="array"==b?[]:{},c;for(c in a)b[c]=goog.cloneObject(a[c]);return b}return a};goog.bindNative_=function(a,b,c){return a.call.apply(a.bind,arguments)};
goog.bindJs_=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}};goog.bind=function(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?goog.bind=goog.bindNative_:goog.bind=goog.bindJs_;return goog.bind.apply(null,arguments)};
goog.partial=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}};goog.mixin=function(a,b){for(var c in b)a[c]=b[c]};goog.now=goog.TRUSTED_SITE&&Date.now||function(){return+new Date};
goog.globalEval=function(a){if(goog.global.execScript)goog.global.execScript(a,"JavaScript");else if(goog.global.eval)if(null==goog.evalWorksForGlobals_&&(goog.global.eval("var _et_ = 1;"),"undefined"!=typeof goog.global._et_?(delete goog.global._et_,goog.evalWorksForGlobals_=!0):goog.evalWorksForGlobals_=!1),goog.evalWorksForGlobals_)goog.global.eval(a);else{var b=goog.global.document,c=b.createElement("script");c.type="text/javascript";c.defer=!1;c.appendChild(b.createTextNode(a));b.body.appendChild(c);
b.body.removeChild(c)}else throw Error("goog.globalEval not available");};goog.evalWorksForGlobals_=null;goog.getCssName=function(a,b){var c=function(a){return goog.cssNameMapping_[a]||a},d=function(a){a=a.split("-");for(var b=[],d=0;d<a.length;d++)b.push(c(a[d]));return b.join("-")},d=goog.cssNameMapping_?"BY_WHOLE"==goog.cssNameMappingStyle_?c:d:function(a){return a};return b?a+"-"+d(b):d(a)};goog.setCssNameMapping=function(a,b){goog.cssNameMapping_=a;goog.cssNameMappingStyle_=b};
!COMPILED&&goog.global.CLOSURE_CSS_NAME_MAPPING&&(goog.cssNameMapping_=goog.global.CLOSURE_CSS_NAME_MAPPING);goog.getMsg=function(a,b){b&&(a=a.replace(/\{\$([^}]+)}/g,function(a,d){return d in b?b[d]:a}));return a};goog.getMsgWithFallback=function(a,b){return a};goog.exportSymbol=function(a,b,c){goog.exportPath_(a,b,c)};goog.exportProperty=function(a,b,c){a[b]=c};
goog.inherits=function(a,b){function c(){}c.prototype=b.prototype;a.superClass_=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var g=Array(arguments.length-2),k=2;k<arguments.length;k++)g[k-2]=arguments[k];return b.prototype[c].apply(a,g)}};
goog.base=function(a,b,c){var d=arguments.callee.caller;if(goog.STRICT_MODE_COMPATIBLE||goog.DEBUG&&!d)throw Error("arguments.caller not defined.  goog.base() cannot be used with strict mode code. See http://www.ecma-international.org/ecma-262/5.1/#sec-C");if(d.superClass_){for(var e=Array(arguments.length-1),f=1;f<arguments.length;f++)e[f-1]=arguments[f];return d.superClass_.constructor.apply(a,e)}e=Array(arguments.length-2);for(f=2;f<arguments.length;f++)e[f-2]=arguments[f];for(var f=!1,g=a.constructor;g;g=
g.superClass_&&g.superClass_.constructor)if(g.prototype[b]===d)f=!0;else if(f)return g.prototype[b].apply(a,e);if(a[b]===d)return a.constructor.prototype[b].apply(a,e);throw Error("goog.base called from a method of one name to a method of a different name");};goog.scope=function(a){a.call(goog.global)};COMPILED||(goog.global.COMPILED=COMPILED);
goog.defineClass=function(a,b){var c=b.constructor,d=b.statics;c&&c!=Object.prototype.constructor||(c=function(){throw Error("cannot instantiate an interface (no constructor defined).");});c=goog.defineClass.createSealingConstructor_(c,a);a&&goog.inherits(c,a);delete b.constructor;delete b.statics;goog.defineClass.applyProperties_(c.prototype,b);null!=d&&(d instanceof Function?d(c):goog.defineClass.applyProperties_(c,d));return c};goog.defineClass.SEAL_CLASS_INSTANCES=goog.DEBUG;
goog.defineClass.createSealingConstructor_=function(a,b){if(goog.defineClass.SEAL_CLASS_INSTANCES&&Object.seal instanceof Function){if(b&&b.prototype&&b.prototype[goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_])return a;var c=function(){var b=a.apply(this,arguments)||this;b[goog.UID_PROPERTY_]=b[goog.UID_PROPERTY_];this.constructor===c&&Object.seal(b);return b};return c}return a};goog.defineClass.OBJECT_PROTOTYPE_FIELDS_="constructor hasOwnProperty isPrototypeOf propertyIsEnumerable toLocaleString toString valueOf".split(" ");
goog.defineClass.applyProperties_=function(a,b){for(var c in b)Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c]);for(var d=0;d<goog.defineClass.OBJECT_PROTOTYPE_FIELDS_.length;d++)c=goog.defineClass.OBJECT_PROTOTYPE_FIELDS_[d],Object.prototype.hasOwnProperty.call(b,c)&&(a[c]=b[c])};goog.tagUnsealableClass=function(a){!COMPILED&&goog.defineClass.SEAL_CLASS_INSTANCES&&(a.prototype[goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_]=!0)};goog.UNSEALABLE_CONSTRUCTOR_PROPERTY_="goog_defineClass_legacy_unsealable";Datafeeds={UDFCompatibleDatafeed:function(a,b){this._datafeedURL=a;this._configuration=void 0;this._symbolsStorage=this._symbolSearch=null;this._barsPulseUpdater=new Datafeeds.DataPulseUpdater(this,b||1E4);this._quotesPulseUpdater=new Datafeeds.QuotesPulseUpdater(this);this._initializationFinished=this._enableLogging=!1;this._callbacks={};this._initialize()}};
Datafeeds.UDFCompatibleDatafeed.prototype.defaultConfiguration=function(){return{supports_search:!0,supports_group_request:!1,supported_resolutions:"1m 3m 5m 15m 30m 60m 120m 240m 360m 720m 1D 2D 3D W 3W 1M".split(" "),supports_marks:!1}};Datafeeds.UDFCompatibleDatafeed.prototype.on=function(a,b){this._callbacks.hasOwnProperty(a)||(this._callbacks[a]=[]);this._callbacks[a].push(b);return this};
Datafeeds.UDFCompatibleDatafeed.prototype._fireEvent=function(a,b){if(this._callbacks.hasOwnProperty(a)){for(var c=this._callbacks[a],d=0;d<c.length;++d)c[d](b);this._callbacks[a]=[]}};Datafeeds.UDFCompatibleDatafeed.prototype.onInitialized=function(){this._initializationFinished=!0;this._fireEvent("initialized")};Datafeeds.UDFCompatibleDatafeed.prototype._logMessage=function(a){if(this._enableLogging){var b=new Date;console.log(b.toLocaleTimeString()+"."+b.getMilliseconds()+"> "+a)}};
Datafeeds.UDFCompatibleDatafeed.prototype._send=function(a,b){var c=a;if(b)for(var d=0;d<Object.keys(b).length;++d)var e=Object.keys(b)[d],f=encodeURIComponent(b[e]),c=c+((0===d?"?":"&")+e+"="+f);this._logMessage("New request: "+c);return $.ajax(c)};Datafeeds.UDFCompatibleDatafeed.prototype._initialize=function(){var a=this;this._send(this._datafeedURL+"/config").done(function(b){b=JSON.parse(b);a._setupWithConfiguration(b)}).fail(function(b){a._setupWithConfiguration(a.defaultConfiguration())})};
Datafeeds.UDFCompatibleDatafeed.prototype.setup=function(a,b){if(this._configuration)this._configuration.engine=a,b(this._configuration);else{var c=this;this.on("configuration_ready",function(){c._configuration.engine=a;b(c._configuration)})}};
Datafeeds.UDFCompatibleDatafeed.prototype._setupWithConfiguration=function(a){this._configuration=a;a.exchanges||(a.exchanges=[]);a.supported_resolutions=a.supported_resolutions||a.supportedResolutions;a.symbols_types=a.symbols_types||a.symbolsTypes;if(!a.supports_search&&!a.supports_group_request)throw"Unsupported datafeed configuration. Must either support search, or support group request";a.supports_search||(this._symbolSearch=new Datafeeds.SymbolSearchComponent(this));if(a.supports_group_request)this._symbolsStorage=
new Datafeeds.SymbolsStorage(this);else this.onInitialized();this._fireEvent("configuration_ready");this._logMessage("Initialized with "+JSON.stringify(a))};Datafeeds.UDFCompatibleDatafeed.prototype.getMarks=function(a,b,c,d,e){this._configuration.supports_marks&&this._send(this._datafeedURL+"/marks",{symbol:a.ticker.toUpperCase(),from:b,to:c,resolution:e}).done(function(a){d(JSON.parse(a))}).fail(function(){d([])})};
Datafeeds.UDFCompatibleDatafeed.prototype.searchSymbolsByName=function(a,b,c,d){if(this._configuration)if(this._configuration.supports_search)this._send(this._datafeedURL+"/search",{limit:30,query:a.toUpperCase(),type:c,exchange:b}).done(function(a){a=JSON.parse(a);for(var b=0;b<a.length;++b)a[b].params||(a[b].params=[]);"undefined"==typeof a.s||"error"!=a.s?d(a):d([])}).fail(function(a){d([])});else{if(!this._symbolSearch)throw"Datafeed error: inconsistent configuration (symbol search)";var e={ticker:a,
exchange:b,type:c,onResultReadyCallback:d};if(this._initializationFinished)this._symbolSearch.searchSymbolsByName(e,30);else{var f=this;this.on("initialized",function(){f._symbolSearch.searchSymbolsByName(e,30)})}}else d([])};Datafeeds.UDFCompatibleDatafeed.prototype._symbolResolveURL="/symbols";
Datafeeds.UDFCompatibleDatafeed.prototype.resolveSymbol=function(a,b,c){function d(a){e.postProcessSymbolInfo&&(a=e.postProcessSymbolInfo(a));b(a)}var e=this;if(this._initializationFinished)if(this._configuration.supports_group_request)if(this._initializationFinished)this._symbolsStorage.resolveSymbol(a,d,c);else this.on("initialized",function(){e._symbolsStorage.resolveSymbol(a,d,c)});else this._send(this._datafeedURL+this._symbolResolveURL,{symbol:a?a.toUpperCase():""}).done(function(a){a=JSON.parse(a);
a.s&&"ok"!=a.s?c("unknown_symbol"):d(a)}).fail(function(a){c("unknown_symbol")});else this.on("initialized",function(){e.resolveSymbol(a,b,c)})};Datafeeds.UDFCompatibleDatafeed.prototype._historyURL="/history";
Datafeeds.UDFCompatibleDatafeed.prototype.getBars=function(a,b,c,d,e,f){if(0<c&&10<(c+"").length)throw"Got a JS time instead of Unix one.";this._send(this._datafeedURL+this._historyURL,{symbol:a.ticker.toUpperCase(),resolution:b,from:c,to:d}).done(function(a){a=JSON.parse(a);if("ok"!=a.s)f&&f(a.s);else{for(var b=[],c=a.t.length,d="undefined"!=typeof a.v,m="undefined"!=typeof a.o,l=0;l<c;++l){var h={time:1E3*a.t[l],close:a.c[l]};m?(h.open=a.o[l],h.high=a.h[l],h.low=a.l[l]):h.open=h.high=h.low=h.close;
d&&(h.volume=a.v[l]);b.push(h)}0===b.length&&f("no data");e(b)}}).fail(function(a){console.warn("getBars(): HTTP error "+JSON.stringify(a));f&&f("network error: "+JSON.stringify(a))})};Datafeeds.UDFCompatibleDatafeed.prototype.subscribeBars=function(a,b,c,d){this._barsPulseUpdater.subscribeDataListener(a,b,c,d)};Datafeeds.UDFCompatibleDatafeed.prototype.unsubscribeBars=function(a){this._barsPulseUpdater.unsubscribeDataListener(a)};
Datafeeds.UDFCompatibleDatafeed.prototype.calculateHistoryDepth=function(a,b,c){};Datafeeds.UDFCompatibleDatafeed.prototype.getQuotes=function(a,b,c){this._send(this._datafeedURL+"/quotes",{symbols:a}).done(function(a){a=JSON.parse(a);"ok"==a.s?b&&b(a.d):c&&c(a.errmsg)}).fail(function(a){c&&c("network error: "+a)})};Datafeeds.UDFCompatibleDatafeed.prototype.subscribeQuotes=function(a,b,c,d){this._quotesPulseUpdater.subscribeDataListener(a,b,c,d)};
Datafeeds.UDFCompatibleDatafeed.prototype.unsubscribeQuotes=function(a){this._quotesPulseUpdater.unsubscribeDataListener(a)};Datafeeds.SymbolsStorage=function(a){this._datafeed=a;this._exchangesList="All Exchanges;BTCe;Bitfinex;Bitstamp;Okcoin;BTCChina;Coinbase;CoinbaseExchange;Campbx;Itbit;Cryptsy;796;Fybsg;Fybse;Kraken;CexIO;Dgex".split(";");this._exchangesWaitingForData={};this._exchangesDataCache={};this._symbolsInfo={};this._symbolsList=[];this._requestFullSymbolsList()};
Datafeeds.SymbolsStorage.prototype._requestFullSymbolsList=function(){for(var a=this,b=0;b<this._exchangesList.length;++b){var c=this._exchangesList[b];this._exchangesDataCache.hasOwnProperty(c)||(this._exchangesDataCache[c]=!0,this._exchangesWaitingForData[c]="waiting_for_data",this._datafeed._send(this._datafeed._datafeedURL+"/symbol_info",{group:c}).done(function(b){return function(c){a._onExchangeDataReceived(b,JSON.parse(c));a._onAnyExchangeResponseReceived(b)}}(c)).fail(function(b){return function(c){a._onAnyExchangeResponseReceived(b)}}(c)))}};
Datafeeds.SymbolsStorage.prototype._onExchangeDataReceived=function(a,b){function c(a,b,c){return a[b]instanceof Array?a[b][c]:a[b]}try{for(var d=0;d<b.symbol.length;++d){var e=b.symbol[d],f=c(b,"exchange-listed",d),g=c(b,"exchange-traded",d),k=g+":"+e,n=c(b,"has-intraday",d),p="undefined"!=typeof b.ticker,m={name:e,base_name:[f+":"+e],description:c(b,"description",d),full_name:k,legs:[k],has_intraday:n,has_no_volume:c(b,"has-no-volume",d),listed_exchange:f,exchange:g,minmov:c(b,"minmovement",d)||
c(b,"minmov",d),pointvalue:c(b,"pointvalue",d),pricescale:c(b,"pricescale",d),type:c(b,"type",d),session:c(b,"session-regular",d),ticker:p?c(b,"ticker",d):e,timezone:c(b,"timezone",d),supported_resolutions:c(b,"supported-resolutions",d)||this._datafeed.defaultConfiguration().supported_resolutions,force_session_rebuild:c(b,"force-session-rebuild",d)||!1,has_daily:c(b,"has-daily",d)||!0,intraday_multipliers:c(b,"intraday-multipliers",d)||["1","5","15","30","60"],has_fractional_volume:c(b,"has-fractional-volume",
d)||!1,has_weekly_and_monthly:c(b,"has-weekly-and-monthly",d)||!1,has_empty_bars:c(b,"has-empty-bars",d)||!1,volume_precision:c(b,"volume-precision",d)||0};this._symbolsInfo[m.ticker]=this._symbolsInfo[e]=this._symbolsInfo[k]=m;this._symbolsList.push(e)}}catch(l){throw"API error when processing exchange `"+a+"` symbol #"+d+": "+l;}};
Datafeeds.SymbolsStorage.prototype._onAnyExchangeResponseReceived=function(a){delete this._exchangesWaitingForData[a];0===Object.keys(this._exchangesWaitingForData).length&&(this._symbolsList.sort(),this._datafeed._logMessage("All exchanges data ready"),this._datafeed.onInitialized())};Datafeeds.SymbolsStorage.prototype.resolveSymbol=function(a,b,c){this._symbolsInfo.hasOwnProperty(a)?b(this._symbolsInfo[a]):c("invalid symbol")};Datafeeds.SymbolSearchComponent=function(a){this._datafeed=a};
Datafeeds.SymbolSearchComponent.prototype.searchSymbolsByName=function(a,b){if(!this._datafeed._symbolsStorage)throw"Cannot use local symbol search when no groups information is available";for(var c=this._datafeed._symbolsStorage,d=[],e=!a.ticker||0===a.ticker.length,f=0;f<c._symbolsList.length;++f){var g=c._symbolsInfo[c._symbolsList[f]];if(!(a.type&&0<a.type.length&&g.type!=a.type||a.exchange&&0<a.exchange.length&&g.exchange!=a.exchange)&&((e||0===g.name.indexOf(a.ticker))&&d.push({symbol:g.name,
full_name:g.full_name,description:g.description,exchange:g.exchange,params:[],type:g.type,ticker:g.name}),d.length>=b))break}a.onResultReadyCallback(d)};
Datafeeds.DataPulseUpdater=function(a,b){this._datafeed=a;this._subscribers={};this._requestsPending=0;var c=this;"undefined"!=typeof b&&0<b&&setInterval(function(){if(!(0<c._requestsPending))for(var a in c._subscribers){var b=c._subscribers[a],f=b.resolution,g=Math.round(Date.now()/1E3),k=g-c.periodLengthSeconds(f,10);c._requestsPending++;(function(b){c._datafeed.getBars(b.symbolInfo,f,k,g,function(e){c._requestsPending--;if(c._subscribers.hasOwnProperty(a)&&0!==e.length){var f=e[e.length-1];if(isNaN(b.lastBarTime)||
!(f.time<b.lastBarTime)){var g=b.listeners;if(!isNaN(b.lastBarTime)&&f.time>b.lastBarTime){if(2>e.length)throw"Not enough bars in history for proper pulse update. Need at least 2.";e=e[e.length-2];for(var h=0;h<g.length;++h)g[h](e)}b.lastBarTime=f.time;for(h=0;h<g.length;++h)g[h](f)}}},function(){c._requestsPending--})})(b)}},b)};Datafeeds.DataPulseUpdater.prototype.unsubscribeDataListener=function(a){this._datafeed._logMessage("Unsubscribing "+a);delete this._subscribers[a]};
Datafeeds.DataPulseUpdater.prototype.subscribeDataListener=function(a,b,c,d){this._datafeed._logMessage("Subscribing "+d);this._subscribers.hasOwnProperty(d)||(this._subscribers[d]={symbolInfo:a,resolution:b,lastBarTime:NaN,listeners:[]});this._subscribers[d].listeners.push(c)};Datafeeds.DataPulseUpdater.prototype.periodLengthSeconds=function(a,b){return 86400*("D"==a?b:"M"==a?31*b:"W"==a?7*b:b*a/1440)};
Datafeeds.QuotesPulseUpdater=function(a){this._datafeed=a;this._subscribers={};this._updateInterval=6E4;this._fastUpdateInterval=1E4;this._requestsPending=0;var b=this;setInterval(function(){b._updateQuotes(function(a){return a.symbols})},this._updateInterval);setInterval(function(){b._updateQuotes(function(a){return 0<a.fastSymbols.length?a.fastSymbols:a.symbols})},this._fastUpdateInterval)};
Datafeeds.QuotesPulseUpdater.prototype.subscribeDataListener=function(a,b,c,d){this._subscribers.hasOwnProperty(d)||(this._subscribers[d]={symbols:a,fastSymbols:b,listeners:[]});this._subscribers[d].listeners.push(c)};Datafeeds.QuotesPulseUpdater.prototype.unsubscribeDataListener=function(a){delete this._subscribers[a]};
Datafeeds.QuotesPulseUpdater.prototype._updateQuotes=function(a){if(!(0<this._requestsPending)){var b=this,c;for(c in this._subscribers){this._requestsPending++;var d=this._subscribers[c];this._datafeed.getQuotes(a(d),function(a,c){return function(d){b._requestsPending--;if(b._subscribers.hasOwnProperty(c))for(var k=0;k<a.length;++k)a[k](d)}}(d.listeners,c),function(a){b._requestsPending--})}}};